name: snack-management

services:
  postgres:
    container_name: snack-postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgres/data
      POSTGRES_DB: snack_db
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - snack
    restart: unless-stopped

  mail-dev:
    container_name: snack-mail-dev
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

volumes:
  postgres:
    driver: local

networks:
  snack:
    driver: bridge